language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - setup=basic

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit